In [37]:
# Notes
# only extracting show data
# highlight num of seasons for chatbot questions

In [38]:
# imports
import csv
import pandas as pd
import os
import datetime
import pymongo
import pprint

In [55]:
# loading in relevant CSVs (show data only)
shows = pd.read_csv('Best Shows Netflix.csv')
shows

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_VOTES,DURATION,NUMBER_OF_SEASONS,MAIN_GENRE,MAIN_PRODUCTION
0,0,Breaking Bad,2008,9.5,1727694,48,5,drama,US
1,1,Avatar: The Last Airbender,2005,9.3,297336,24,3,scifi,US
2,2,Our Planet,2019,9.3,41386,50,1,documentary,GB
3,3,Kota Factory,2019,9.3,66985,42,2,drama,IN
4,4,The Last Dance,2020,9.1,108321,50,1,documentary,US
...,...,...,...,...,...,...,...,...,...
241,241,Evil Genius,2018,7.5,27516,48,1,crime,US
242,242,13 Reasons Why,2017,7.5,282373,58,4,drama,US
243,243,Lupin,2021,7.5,100575,46,3,crime,FR
244,244,All of Us Are Dead,2022,7.5,41393,61,1,action,KR
245,245,I Am Not Okay with This,2020,7.5,56459,21,1,comedy,US

In [57]:
# only using SCORE column to determine show ranking, so don't need NUMBER_OF_VOTES column
shows.drop('NUMBER_OF_VOTES', axis = 1)

,index,TITLE,RELEASE_YEAR,SCORE,DURATION,NUMBER_OF_SEASONS,MAIN_GENRE,MAIN_PRODUCTION
0,0,Breaking Bad,2008,9.5,48,5,drama,US
1,1,Avatar: The Last Airbender,2005,9.3,24,3,scifi,US
2,2,Our Planet,2019,9.3,50,1,documentary,GB
3,3,Kota Factory,2019,9.3,42,2,drama,IN
4,4,The Last Dance,2020,9.1,50,1,documentary,US
...,...,...,...,...,...,...,...,...
241,241,Evil Genius,2018,7.5,48,1,crime,US
242,242,13 Reasons Why,2017,7.5,58,4,drama,US
243,243,Lupin,2021,7.5,46,3,crime,FR
244,244,All of Us Are Dead,2022,7.5,61,1,action,KR
245,245,I Am Not Okay with This,2020,7.5,21,1,comedy,US

In [4]:
shows_year = pd.read_csv('Best Show by Year Netflix.csv')
shows_year

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_SEASONS,MAIN_GENRE,MAIN_PRODUCTION
0,0,Monty Python's Flying Circus,1969,8.8,4,comedy,GB
1,1,Knight Rider,1982,6.9,4,action,US
2,2,Seinfeld,1989,8.9,9,comedy,US
3,3,Star Trek: Deep Space Nine,1993,8.1,7,scifi,US
4,4,Neon Genesis Evangelion,1995,8.5,1,scifi,JP
5,5,Stargate SG-1,1997,8.4,10,scifi,US
6,6,Cowboy Bebop,1998,8.9,1,western,JP
7,7,One Piece,1999,8.8,21,action,JP
8,8,Gilmore Girls,2000,8.2,8,comedy,US
9,9,Trailer Park Boys,2001,8.6,12,comedy,CA
10,10,Naruto,2002,8.4,6,scifi,JP
11,11,Chappelle's Show,2003,8.8,3,comedy,US
12,12,The 4400,2004,7.3,4,scifi,US
13,13,Avatar: The Last Airbender,2005,9.3,3,scifi,US
14,14,DEATH NOTE,2006,9.0,1,scifi,JP
15,15,iCarly,2007,6.7,6,comedy,US
16,16,Breaking Bad,2008,9.5,5,drama,US
17,17,Community,2009,8.5,6,comedy,US
18,18,Downton Abbey,2010,8.7,6,drama,GB
19,19,Hunter x Hunter,2011,9.0,3,drama,JP
20,20,Call the Midwife,2012,8.5,11,drama,GB
21,21,Attack on Titan,2013,9.0,4,scifi,JP
22,22,BoJack Horseman,2014,8.8,6,drama,US
23,23,Better Call Saul,2015,8.8,6,comedy,US
24,24,Stranger Things,2016,8.7,5,scifi,US
25,25,Anne with an E,2017,8.7,3,drama,CA
26,26,Cobra Kai,2018,8.6,5,action,US
27,27,Kota Factory,2019,9.3,2,drama,IN
28,28,The Last Dance,2020,9.1,1,documentary,US
29,29,Arcane,2021,9.1,1,action,US
30,30,Heartstopper,2022,8.9,1,drama,GB

In [61]:
# only using MAIN_PRODUCTION column from general df, so don't need it here 
shows_year.drop('MAIN_PRODUCTION', axis = 1)

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_SEASONS,MAIN_GENRE
0,0,Monty Python's Flying Circus,1969,8.8,4,comedy
1,1,Knight Rider,1982,6.9,4,action
2,2,Seinfeld,1989,8.9,9,comedy
3,3,Star Trek: Deep Space Nine,1993,8.1,7,scifi
4,4,Neon Genesis Evangelion,1995,8.5,1,scifi
5,5,Stargate SG-1,1997,8.4,10,scifi
6,6,Cowboy Bebop,1998,8.9,1,western
7,7,One Piece,1999,8.8,21,action
8,8,Gilmore Girls,2000,8.2,8,comedy
9,9,Trailer Park Boys,2001,8.6,12,comedy
10,10,Naruto,2002,8.4,6,scifi
11,11,Chappelle's Show,2003,8.8,3,comedy
12,12,The 4400,2004,7.3,4,scifi
13,13,Avatar: The Last Airbender,2005,9.3,3,scifi
14,14,DEATH NOTE,2006,9.0,1,scifi
15,15,iCarly,2007,6.7,6,comedy
16,16,Breaking Bad,2008,9.5,5,drama
17,17,Community,2009,8.5,6,comedy
18,18,Downton Abbey,2010,8.7,6,drama
19,19,Hunter x Hunter,2011,9.0,3,drama
20,20,Call the Midwife,2012,8.5,11,drama
21,21,Attack on Titan,2013,9.0,4,scifi
22,22,BoJack Horseman,2014,8.8,6,drama
23,23,Better Call Saul,2015,8.8,6,comedy
24,24,Stranger Things,2016,8.7,5,scifi
25,25,Anne with an E,2017,8.7,3,drama
26,26,Cobra Kai,2018,8.6,5,action
27,27,Kota Factory,2019,9.3,2,drama
28,28,The Last Dance,2020,9.1,1,documentary
29,29,Arcane,2021,9.1,1,action
30,30,Heartstopper,2022,8.9,1,drama

In [6]:
# connecting to MongoDB
host_name = "localhost"
port = "27017"

atlas_cluster_name = "sandbox"
atlas_default_dbname = "local"

In [7]:
conn_str = {
    "local" : f"mongodb://{host_name}:{port}/",
#    "atlas" : f"mongodb+srv://{atlas_user_name}:{atlas_password}@{atlas_cluster_name}.zibbf.mongodb.net/{atlas_default_dbname}"
}

client = pymongo.MongoClient(conn_str["local"])

print(f"Local Connection String: {conn_str['local']}")

Local Connection String: mongodb://localhost:27017/

In [11]:
# creating a MongoDB
db = client['shows']
client.list_database_names()

['admin', 'config', 'local']

In [28]:
# creating a Mongo collection
collection = db.collection.insert_many(shows.to_dict('records'))

In [29]:
# checking Mongo collection lists
db.list_collection_names()

['collection']

In [59]:
# create MongoDB connection for shows by_year
host_name = "localhost"
port = "27017"

atlas_cluster_name = "sandbox"
atlas_default_dbname = "local"

In [60]:
conn_str = {
    "local" : f"mongodb://{host_name}:{port}/",
#    "atlas" : f"mongodb+srv://{atlas_user_name}:{atlas_password}@{atlas_cluster_name}.zibbf.mongodb.net/{atlas_default_dbname}"
}

client = pymongo.MongoClient(conn_str["local"])

print(f"Local Connection String: {conn_str['local']}")

Local Connection String: mongodb://localhost:27017/

In [62]:
# creating a MongoDB for shows_year
db2 = client['shows_year']
client.list_database_names()

['admin', 'config', 'local', 'shows']

In [66]:
# creating a Mongo collection for shows_year
collection2 = db2.collection2.insert_many(shows.to_dict('records'))

In [67]:
# checking updated Mongo collection lists
db2.list_collection_names()

['collection', 'collection2']

In [34]:
# checking all values from pandas df are in new MongoDB
pprint.pprint(collection.inserted_ids)

[ObjectId('6394eed7f760f3c3f2fb922c'),
 ObjectId('6394eed7f760f3c3f2fb922d'),
 ObjectId('6394eed7f760f3c3f2fb922e'),
 ObjectId('6394eed7f760f3c3f2fb922f'),
 ObjectId('6394eed7f760f3c3f2fb9230'),
 ObjectId('6394eed7f760f3c3f2fb9231'),
 ObjectId('6394eed7f760f3c3f2fb9232'),
 ObjectId('6394eed7f760f3c3f2fb9233'),
 ObjectId('6394eed7f760f3c3f2fb9234'),
 ObjectId('6394eed7f760f3c3f2fb9235'),
 ObjectId('6394eed7f760f3c3f2fb9236'),
 ObjectId('6394eed7f760f3c3f2fb9237'),
 ObjectId('6394eed7f760f3c3f2fb9238'),
 ObjectId('6394eed7f760f3c3f2fb9239'),
 ObjectId('6394eed7f760f3c3f2fb923a'),
 ObjectId('6394eed7f760f3c3f2fb923b'),
 ObjectId('6394eed7f760f3c3f2fb923c'),
 ObjectId('6394eed7f760f3c3f2fb923d'),
 ObjectId('6394eed7f760f3c3f2fb923e'),
 ObjectId('6394eed7f760f3c3f2fb923f'),
 ObjectId('6394eed7f760f3c3f2fb9240'),
 ObjectId('6394eed7f760f3c3f2fb9241'),
 ObjectId('6394eed7f760f3c3f2fb9242'),
 ObjectId('6394eed7f760f3c3f2fb9243'),
 ObjectId('6394eed7f760f3c3f2fb9244'),
 ObjectId('6394eed7f760f3c3f2fb9245'),
 ObjectId('6394eed7f760f3c3f2fb9246'),
 ObjectId('6394eed7f760f3c3f2fb9247'),
 ObjectId('6394eed7f760f3c3f2fb9248'),
 ObjectId('6394eed7f760f3c3f2fb9249'),
 ObjectId('6394eed7f760f3c3f2fb924a'),
 ObjectId('6394eed7f760f3c3f2fb924b'),
 ObjectId('6394eed7f760f3c3f2fb924c'),
 ObjectId('6394eed7f760f3c3f2fb924d'),
 ObjectId('6394eed7f760f3c3f2fb924e'),
 ObjectId('6394eed7f760f3c3f2fb924f'),
 ObjectId('6394eed7f760f3c3f2fb9250'),
 ObjectId('6394eed7f760f3c3f2fb9251'),
 ObjectId('6394eed7f760f3c3f2fb9252'),
 ObjectId('6394eed7f760f3c3f2fb9253'),
 ObjectId('6394eed7f760f3c3f2fb9254'),
 ObjectId('6394eed7f760f3c3f2fb9255'),
 ObjectId('6394eed7f760f3c3f2fb9256'),
 ObjectId('6394eed7f760f3c3f2fb9257'),
 ObjectId('6394eed7f760f3c3f2fb9258'),
 ObjectId('6394eed7f760f3c3f2fb9259'),
 ObjectId('6394eed7f760f3c3f2fb925a'),
 ObjectId('6394eed7f760f3c3f2fb925b'),
 ObjectId('6394eed7f760f3c3f2fb925c'),
 ObjectId('6394eed7f760f3c3f2fb925d'),
 ObjectId('6394eed7f760f3c3f2fb925e'),
 ObjectId('6394eed7f760f3c3f2fb925f'),
 ObjectId('6394eed7f760f3c3f2fb9260'),
 ObjectId('6394eed7f760f3c3f2fb9261'),
 ObjectId('6394eed7f760f3c3f2fb9262'),
 ObjectId('6394eed7f760f3c3f2fb9263'),
 ObjectId('6394eed7f760f3c3f2fb9264'),
 ObjectId('6394eed7f760f3c3f2fb9265'),
 ObjectId('6394eed7f760f3c3f2fb9266'),
 ObjectId('6394eed7f760f3c3f2fb9267'),
 ObjectId('6394eed7f760f3c3f2fb9268'),
 ObjectId('6394eed7f760f3c3f2fb9269'),
 ObjectId('6394eed7f760f3c3f2fb926a'),
 ObjectId('6394eed7f760f3c3f2fb926b'),
 ObjectId('6394eed7f760f3c3f2fb926c'),
 ObjectId('6394eed7f760f3c3f2fb926d'),
 ObjectId('6394eed7f760f3c3f2fb926e'),
 ObjectId('6394eed7f760f3c3f2fb926f'),
 ObjectId('6394eed7f760f3c3f2fb9270'),
 ObjectId('6394eed7f760f3c3f2fb9271'),
 ObjectId('6394eed7f760f3c3f2fb9272'),
 ObjectId('6394eed7f760f3c3f2fb9273'),
 ObjectId('6394eed7f760f3c3f2fb9274'),
 ObjectId('6394eed7f760f3c3f2fb9275'),
 ObjectId('6394eed7f760f3c3f2fb9276'),
 ObjectId('6394eed7f760f3c3f2fb9277'),
 ObjectId('6394eed7f760f3c3f2fb9278'),
 ObjectId('6394eed7f760f3c3f2fb9279'),
 ObjectId('6394eed7f760f3c3f2fb927a'),
 ObjectId('6394eed7f760f3c3f2fb927b'),
 ObjectId('6394eed7f760f3c3f2fb927c'),
 ObjectId('6394eed7f760f3c3f2fb927d'),
 ObjectId('6394eed7f760f3c3f2fb927e'),
 ObjectId('6394eed7f760f3c3f2fb927f'),
 ObjectId('6394eed7f760f3c3f2fb9280'),
 ObjectId('6394eed7f760f3c3f2fb9281'),
 ObjectId('6394eed7f760f3c3f2fb9282'),
 ObjectId('6394eed7f760f3c3f2fb9283'),
 ObjectId('6394eed7f760f3c3f2fb9284'),
 ObjectId('6394eed7f760f3c3f2fb9285'),
 ObjectId('6394eed7f760f3c3f2fb9286'),
 ObjectId('6394eed7f760f3c3f2fb9287'),
 ObjectId('6394eed7f760f3c3f2fb9288'),
 ObjectId('6394eed7f760f3c3f2fb9289'),
 ObjectId('6394eed7f760f3c3f2fb928a'),
 ObjectId('6394eed7f760f3c3f2fb928b'),
 ObjectId('6394eed7f760f3c3f2fb928c'),
 ObjectId('6394eed7f760f3c3f2fb928d'),
 ObjectId('6394eed7f760f3c3f2fb928e'),
 ObjectId('6394eed7f760f3c3f2fb928f'),
 ObjectId('6394eed7f760f3c3f2fb9290'),
 ObjectId('6394eed7f760f3c3f2fb9291'),
 ObjectId('6394eed7f760f3c3f2fb9292'),
 ObjectId('6394eed7f760f3c3f2fb9293'),
 ObjectId('6394eed7f760f3c3f2fb9294'),
 ObjectId('6394eed7f760f3c3f2fb9295'),
 ObjectId('6394eed7f760f3c3f2fb9296'),
 ObjectId('6394eed7f760f3c3f2fb9297'),
 ObjectId('6394eed7f760f3c3f2fb9298'),
 ObjectId('6394eed7f760f3c3f2fb9299'),
 ObjectId('6394eed7f760f3c3f2fb929a'),
 ObjectId('6394eed7f760f3c3f2fb929b'),
 ObjectId('6394eed7f760f3c3f2fb929c'),
 ObjectId('6394eed7f760f3c3f2fb929d'),
 ObjectId('6394eed7f760f3c3f2fb929e'),
 ObjectId('6394eed7f760f3c3f2fb929f'),
 ObjectId('6394eed7f760f3c3f2fb92a0'),
 ObjectId('6394eed7f760f3c3f2fb92a1'),
 ObjectId('6394eed7f760f3c3f2fb92a2'),
 ObjectId('6394eed7f760f3c3f2fb92a3'),
 ObjectId('6394eed7f760f3c3f2fb92a4'),
 ObjectId('6394eed7f760f3c3f2fb92a5'),
 ObjectId('6394eed7f760f3c3f2fb92a6'),
 ObjectId('6394eed7f760f3c3f2fb92a7'),
 ObjectId('6394eed7f760f3c3f2fb92a8'),
 ObjectId('6394eed7f760f3c3f2fb92a9'),
 ObjectId('6394eed7f760f3c3f2fb92aa'),
 ObjectId('6394eed7f760f3c3f2fb92ab'),
 ObjectId('6394eed7f760f3c3f2fb92ac'),
 ObjectId('6394eed7f760f3c3f2fb92ad'),
 ObjectId('6394eed7f760f3c3f2fb92ae'),
 ObjectId('6394eed7f760f3c3f2fb92af'),
 ObjectId('6394eed7f760f3c3f2fb92b0'),
 ObjectId('6394eed7f760f3c3f2fb92b1'),
 ObjectId('6394eed7f760f3c3f2fb92b2'),
 ObjectId('6394eed7f760f3c3f2fb92b3'),
 ObjectId('6394eed7f760f3c3f2fb92b4'),
 ObjectId('6394eed7f760f3c3f2fb92b5'),
 ObjectId('6394eed7f760f3c3f2fb92b6'),
 ObjectId('6394eed7f760f3c3f2fb92b7'),
 ObjectId('6394eed7f760f3c3f2fb92b8'),
 ObjectId('6394eed7f760f3c3f2fb92b9'),
 ObjectId('6394eed7f760f3c3f2fb92ba'),
 ObjectId('6394eed7f760f3c3f2fb92bb'),
 ObjectId('6394eed7f760f3c3f2fb92bc'),
 ObjectId('6394eed7f760f3c3f2fb92bd'),
 ObjectId('6394eed7f760f3c3f2fb92be'),
 ObjectId('6394eed7f760f3c3f2fb92bf'),
 ObjectId('6394eed7f760f3c3f2fb92c0'),
 ObjectId('6394eed7f760f3c3f2fb92c1'),
 ObjectId('6394eed7f760f3c3f2fb92c2'),
 ObjectId('6394eed7f760f3c3f2fb92c3'),
 ObjectId('6394eed7f760f3c3f2fb92c4'),
 ObjectId('6394eed7f760f3c3f2fb92c5'),
 ObjectId('6394eed7f760f3c3f2fb92c6'),
 ObjectId('6394eed7f760f3c3f2fb92c7'),
 ObjectId('6394eed7f760f3c3f2fb92c8'),
 ObjectId('6394eed7f760f3c3f2fb92c9'),
 ObjectId('6394eed7f760f3c3f2fb92ca'),
 ObjectId('6394eed7f760f3c3f2fb92cb'),
 ObjectId('6394eed7f760f3c3f2fb92cc'),
 ObjectId('6394eed7f760f3c3f2fb92cd'),
 ObjectId('6394eed7f760f3c3f2fb92ce'),
 ObjectId('6394eed7f760f3c3f2fb92cf'),
 ObjectId('6394eed7f760f3c3f2fb92d0'),
 ObjectId('6394eed7f760f3c3f2fb92d1'),
 ObjectId('6394eed7f760f3c3f2fb92d2'),
 ObjectId('6394eed7f760f3c3f2fb92d3'),
 ObjectId('6394eed7f760f3c3f2fb92d4'),
 ObjectId('6394eed7f760f3c3f2fb92d5'),
 ObjectId('6394eed7f760f3c3f2fb92d6'),
 ObjectId('6394eed7f760f3c3f2fb92d7'),
 ObjectId('6394eed7f760f3c3f2fb92d8'),
 ObjectId('6394eed7f760f3c3f2fb92d9'),
 ObjectId('6394eed7f760f3c3f2fb92da'),
 ObjectId('6394eed7f760f3c3f2fb92db'),
 ObjectId('6394eed7f760f3c3f2fb92dc'),
 ObjectId('6394eed7f760f3c3f2fb92dd'),
 ObjectId('6394eed7f760f3c3f2fb92de'),
 ObjectId('6394eed7f760f3c3f2fb92df'),
 ObjectId('6394eed7f760f3c3f2fb92e0'),
 ObjectId('6394eed7f760f3c3f2fb92e1'),
 ObjectId('6394eed7f760f3c3f2fb92e2'),
 ObjectId('6394eed7f760f3c3f2fb92e3'),
 ObjectId('6394eed7f760f3c3f2fb92e4'),
 ObjectId('6394eed7f760f3c3f2fb92e5'),
 ObjectId('6394eed7f760f3c3f2fb92e6'),
 ObjectId('6394eed7f760f3c3f2fb92e7'),
 ObjectId('6394eed7f760f3c3f2fb92e8'),
 ObjectId('6394eed7f760f3c3f2fb92e9'),
 ObjectId('6394eed7f760f3c3f2fb92ea'),
 ObjectId('6394eed7f760f3c3f2fb92eb'),
 ObjectId('6394eed7f760f3c3f2fb92ec'),
 ObjectId('6394eed7f760f3c3f2fb92ed'),
 ObjectId('6394eed7f760f3c3f2fb92ee'),
 ObjectId('6394eed7f760f3c3f2fb92ef'),
 ObjectId('6394eed7f760f3c3f2fb92f0'),
 ObjectId('6394eed7f760f3c3f2fb92f1'),
 ObjectId('6394eed7f760f3c3f2fb92f2'),
 ObjectId('6394eed7f760f3c3f2fb92f3'),
 ObjectId('6394eed7f760f3c3f2fb92f4'),
 ObjectId('6394eed7f760f3c3f2fb92f5'),
 ObjectId('6394eed7f760f3c3f2fb92f6'),
 ObjectId('6394eed7f760f3c3f2fb92f7'),
 ObjectId('6394eed7f760f3c3f2fb92f8'),
 ObjectId('6394eed7f760f3c3f2fb92f9'),
 ObjectId('6394eed7f760f3c3f2fb92fa'),
 ObjectId('6394eed7f760f3c3f2fb92fb'),
 ObjectId('6394eed7f760f3c3f2fb92fc'),
 ObjectId('6394eed7f760f3c3f2fb92fd'),
 ObjectId('6394eed7f760f3c3f2fb92fe'),
 ObjectId('6394eed7f760f3c3f2fb92ff'),
 ObjectId('6394eed7f760f3c3f2fb9300'),
 ObjectId('6394eed7f760f3c3f2fb9301'),
 ObjectId('6394eed7f760f3c3f2fb9302'),
 ObjectId('6394eed7f760f3c3f2fb9303'),
 ObjectId('6394eed7f760f3c3f2fb9304'),
 ObjectId('6394eed7f760f3c3f2fb9305'),
 ObjectId('6394eed7f760f3c3f2fb9306'),
 ObjectId('6394eed7f760f3c3f2fb9307'),
 ObjectId('6394eed7f760f3c3f2fb9308'),
 ObjectId('6394eed7f760f3c3f2fb9309'),
 ObjectId('6394eed7f760f3c3f2fb930a'),
 ObjectId('6394eed7f760f3c3f2fb930b'),
 ObjectId('6394eed7f760f3c3f2fb930c'),
 ObjectId('6394eed7f760f3c3f2fb930d'),
 ObjectId('6394eed7f760f3c3f2fb930e'),
 ObjectId('6394eed7f760f3c3f2fb930f'),
 ObjectId('6394eed7f760f3c3f2fb9310'),
 ObjectId('6394eed7f760f3c3f2fb9311'),
 ObjectId('6394eed7f760f3c3f2fb9312'),
 ObjectId('6394eed7f760f3c3f2fb9313'),
 ObjectId('6394eed7f760f3c3f2fb9314'),
 ObjectId('6394eed7f760f3c3f2fb9315'),
 ObjectId('6394eed7f760f3c3f2fb9316'),
 ObjectId('6394eed7f760f3c3f2fb9317'),
 ObjectId('6394eed7f760f3c3f2fb9318'),
 ObjectId('6394eed7f760f3c3f2fb9319'),
 ObjectId('6394eed7f760f3c3f2fb931a'),
 ObjectId('6394eed7f760f3c3f2fb931b'),
 ObjectId('6394eed7f760f3c3f2fb931c'),
 ObjectId('6394eed7f760f3c3f2fb931d'),
 ObjectId('6394eed7f760f3c3f2fb931e'),
 ObjectId('6394eed7f760f3c3f2fb931f'),
 ObjectId('6394eed7f760f3c3f2fb9320'),
 ObjectId('6394eed7f760f3c3f2fb9321')]

In [68]:
# checking all values from pandas df (shows_year) are in new MongoDB
pprint.pprint(collection2.inserted_ids)

[ObjectId('6395010cf760f3c3f2fb9605'),
 ObjectId('6395010cf760f3c3f2fb9606'),
 ObjectId('6395010cf760f3c3f2fb9607'),
 ObjectId('6395010cf760f3c3f2fb9608'),
 ObjectId('6395010cf760f3c3f2fb9609'),
 ObjectId('6395010cf760f3c3f2fb960a'),
 ObjectId('6395010cf760f3c3f2fb960b'),
 ObjectId('6395010cf760f3c3f2fb960c'),
 ObjectId('6395010cf760f3c3f2fb960d'),
 ObjectId('6395010cf760f3c3f2fb960e'),
 ObjectId('6395010cf760f3c3f2fb960f'),
 ObjectId('6395010cf760f3c3f2fb9610'),
 ObjectId('6395010cf760f3c3f2fb9611'),
 ObjectId('6395010cf760f3c3f2fb9612'),
 ObjectId('6395010cf760f3c3f2fb9613'),
 ObjectId('6395010cf760f3c3f2fb9614'),
 ObjectId('6395010cf760f3c3f2fb9615'),
 ObjectId('6395010cf760f3c3f2fb9616'),
 ObjectId('6395010cf760f3c3f2fb9617'),
 ObjectId('6395010cf760f3c3f2fb9618'),
 ObjectId('6395010cf760f3c3f2fb9619'),
 ObjectId('6395010cf760f3c3f2fb961a'),
 ObjectId('6395010cf760f3c3f2fb961b'),
 ObjectId('6395010cf760f3c3f2fb961c'),
 ObjectId('6395010cf760f3c3f2fb961d'),
 ObjectId('6395010cf760f3c3f2fb961e'),
 ObjectId('6395010cf760f3c3f2fb961f'),
 ObjectId('6395010cf760f3c3f2fb9620'),
 ObjectId('6395010cf760f3c3f2fb9621'),
 ObjectId('6395010cf760f3c3f2fb9622'),
 ObjectId('6395010cf760f3c3f2fb9623'),
 ObjectId('6395010cf760f3c3f2fb9624'),
 ObjectId('6395010cf760f3c3f2fb9625'),
 ObjectId('6395010cf760f3c3f2fb9626'),
 ObjectId('6395010cf760f3c3f2fb9627'),
 ObjectId('6395010cf760f3c3f2fb9628'),
 ObjectId('6395010cf760f3c3f2fb9629'),
 ObjectId('6395010cf760f3c3f2fb962a'),
 ObjectId('6395010cf760f3c3f2fb962b'),
 ObjectId('6395010cf760f3c3f2fb962c'),
 ObjectId('6395010cf760f3c3f2fb962d'),
 ObjectId('6395010cf760f3c3f2fb962e'),
 ObjectId('6395010cf760f3c3f2fb962f'),
 ObjectId('6395010cf760f3c3f2fb9630'),
 ObjectId('6395010cf760f3c3f2fb9631'),
 ObjectId('6395010cf760f3c3f2fb9632'),
 ObjectId('6395010cf760f3c3f2fb9633'),
 ObjectId('6395010cf760f3c3f2fb9634'),
 ObjectId('6395010cf760f3c3f2fb9635'),
 ObjectId('6395010cf760f3c3f2fb9636'),
 ObjectId('6395010cf760f3c3f2fb9637'),
 ObjectId('6395010cf760f3c3f2fb9638'),
 ObjectId('6395010cf760f3c3f2fb9639'),
 ObjectId('6395010cf760f3c3f2fb963a'),
 ObjectId('6395010cf760f3c3f2fb963b'),
 ObjectId('6395010cf760f3c3f2fb963c'),
 ObjectId('6395010cf760f3c3f2fb963d'),
 ObjectId('6395010cf760f3c3f2fb963e'),
 ObjectId('6395010cf760f3c3f2fb963f'),
 ObjectId('6395010cf760f3c3f2fb9640'),
 ObjectId('6395010cf760f3c3f2fb9641'),
 ObjectId('6395010cf760f3c3f2fb9642'),
 ObjectId('6395010cf760f3c3f2fb9643'),
 ObjectId('6395010cf760f3c3f2fb9644'),
 ObjectId('6395010cf760f3c3f2fb9645'),
 ObjectId('6395010cf760f3c3f2fb9646'),
 ObjectId('6395010cf760f3c3f2fb9647'),
 ObjectId('6395010cf760f3c3f2fb9648'),
 ObjectId('6395010cf760f3c3f2fb9649'),
 ObjectId('6395010cf760f3c3f2fb964a'),
 ObjectId('6395010cf760f3c3f2fb964b'),
 ObjectId('6395010cf760f3c3f2fb964c'),
 ObjectId('6395010cf760f3c3f2fb964d'),
 ObjectId('6395010cf760f3c3f2fb964e'),
 ObjectId('6395010cf760f3c3f2fb964f'),
 ObjectId('6395010cf760f3c3f2fb9650'),
 ObjectId('6395010cf760f3c3f2fb9651'),
 ObjectId('6395010cf760f3c3f2fb9652'),
 ObjectId('6395010cf760f3c3f2fb9653'),
 ObjectId('6395010cf760f3c3f2fb9654'),
 ObjectId('6395010cf760f3c3f2fb9655'),
 ObjectId('6395010cf760f3c3f2fb9656'),
 ObjectId('6395010cf760f3c3f2fb9657'),
 ObjectId('6395010cf760f3c3f2fb9658'),
 ObjectId('6395010cf760f3c3f2fb9659'),
 ObjectId('6395010cf760f3c3f2fb965a'),
 ObjectId('6395010cf760f3c3f2fb965b'),
 ObjectId('6395010cf760f3c3f2fb965c'),
 ObjectId('6395010cf760f3c3f2fb965d'),
 ObjectId('6395010cf760f3c3f2fb965e'),
 ObjectId('6395010cf760f3c3f2fb965f'),
 ObjectId('6395010cf760f3c3f2fb9660'),
 ObjectId('6395010cf760f3c3f2fb9661'),
 ObjectId('6395010cf760f3c3f2fb9662'),
 ObjectId('6395010cf760f3c3f2fb9663'),
 ObjectId('6395010cf760f3c3f2fb9664'),
 ObjectId('6395010cf760f3c3f2fb9665'),
 ObjectId('6395010cf760f3c3f2fb9666'),
 ObjectId('6395010cf760f3c3f2fb9667'),
 ObjectId('6395010cf760f3c3f2fb9668'),
 ObjectId('6395010cf760f3c3f2fb9669'),
 ObjectId('6395010cf760f3c3f2fb966a'),
 ObjectId('6395010cf760f3c3f2fb966b'),
 ObjectId('6395010cf760f3c3f2fb966c'),
 ObjectId('6395010cf760f3c3f2fb966d'),
 ObjectId('6395010cf760f3c3f2fb966e'),
 ObjectId('6395010cf760f3c3f2fb966f'),
 ObjectId('6395010cf760f3c3f2fb9670'),
 ObjectId('6395010cf760f3c3f2fb9671'),
 ObjectId('6395010cf760f3c3f2fb9672'),
 ObjectId('6395010cf760f3c3f2fb9673'),
 ObjectId('6395010cf760f3c3f2fb9674'),
 ObjectId('6395010cf760f3c3f2fb9675'),
 ObjectId('6395010cf760f3c3f2fb9676'),
 ObjectId('6395010cf760f3c3f2fb9677'),
 ObjectId('6395010cf760f3c3f2fb9678'),
 ObjectId('6395010cf760f3c3f2fb9679'),
 ObjectId('6395010cf760f3c3f2fb967a'),
 ObjectId('6395010cf760f3c3f2fb967b'),
 ObjectId('6395010cf760f3c3f2fb967c'),
 ObjectId('6395010cf760f3c3f2fb967d'),
 ObjectId('6395010cf760f3c3f2fb967e'),
 ObjectId('6395010cf760f3c3f2fb967f'),
 ObjectId('6395010cf760f3c3f2fb9680'),
 ObjectId('6395010cf760f3c3f2fb9681'),
 ObjectId('6395010cf760f3c3f2fb9682'),
 ObjectId('6395010cf760f3c3f2fb9683'),
 ObjectId('6395010cf760f3c3f2fb9684'),
 ObjectId('6395010cf760f3c3f2fb9685'),
 ObjectId('6395010cf760f3c3f2fb9686'),
 ObjectId('6395010cf760f3c3f2fb9687'),
 ObjectId('6395010cf760f3c3f2fb9688'),
 ObjectId('6395010cf760f3c3f2fb9689'),
 ObjectId('6395010cf760f3c3f2fb968a'),
 ObjectId('6395010cf760f3c3f2fb968b'),
 ObjectId('6395010cf760f3c3f2fb968c'),
 ObjectId('6395010cf760f3c3f2fb968d'),
 ObjectId('6395010cf760f3c3f2fb968e'),
 ObjectId('6395010cf760f3c3f2fb968f'),
 ObjectId('6395010cf760f3c3f2fb9690'),
 ObjectId('6395010cf760f3c3f2fb9691'),
 ObjectId('6395010cf760f3c3f2fb9692'),
 ObjectId('6395010cf760f3c3f2fb9693'),
 ObjectId('6395010cf760f3c3f2fb9694'),
 ObjectId('6395010cf760f3c3f2fb9695'),
 ObjectId('6395010cf760f3c3f2fb9696'),
 ObjectId('6395010cf760f3c3f2fb9697'),
 ObjectId('6395010cf760f3c3f2fb9698'),
 ObjectId('6395010cf760f3c3f2fb9699'),
 ObjectId('6395010cf760f3c3f2fb969a'),
 ObjectId('6395010cf760f3c3f2fb969b'),
 ObjectId('6395010cf760f3c3f2fb969c'),
 ObjectId('6395010cf760f3c3f2fb969d'),
 ObjectId('6395010cf760f3c3f2fb969e'),
 ObjectId('6395010cf760f3c3f2fb969f'),
 ObjectId('6395010cf760f3c3f2fb96a0'),
 ObjectId('6395010cf760f3c3f2fb96a1'),
 ObjectId('6395010cf760f3c3f2fb96a2'),
 ObjectId('6395010cf760f3c3f2fb96a3'),
 ObjectId('6395010cf760f3c3f2fb96a4'),
 ObjectId('6395010cf760f3c3f2fb96a5'),
 ObjectId('6395010cf760f3c3f2fb96a6'),
 ObjectId('6395010cf760f3c3f2fb96a7'),
 ObjectId('6395010cf760f3c3f2fb96a8'),
 ObjectId('6395010cf760f3c3f2fb96a9'),
 ObjectId('6395010cf760f3c3f2fb96aa'),
 ObjectId('6395010cf760f3c3f2fb96ab'),
 ObjectId('6395010cf760f3c3f2fb96ac'),
 ObjectId('6395010cf760f3c3f2fb96ad'),
 ObjectId('6395010cf760f3c3f2fb96ae'),
 ObjectId('6395010cf760f3c3f2fb96af'),
 ObjectId('6395010cf760f3c3f2fb96b0'),
 ObjectId('6395010cf760f3c3f2fb96b1'),
 ObjectId('6395010cf760f3c3f2fb96b2'),
 ObjectId('6395010cf760f3c3f2fb96b3'),
 ObjectId('6395010cf760f3c3f2fb96b4'),
 ObjectId('6395010cf760f3c3f2fb96b5'),
 ObjectId('6395010cf760f3c3f2fb96b6'),
 ObjectId('6395010cf760f3c3f2fb96b7'),
 ObjectId('6395010cf760f3c3f2fb96b8'),
 ObjectId('6395010cf760f3c3f2fb96b9'),
 ObjectId('6395010cf760f3c3f2fb96ba'),
 ObjectId('6395010cf760f3c3f2fb96bb'),
 ObjectId('6395010cf760f3c3f2fb96bc'),
 ObjectId('6395010cf760f3c3f2fb96bd'),
 ObjectId('6395010cf760f3c3f2fb96be'),
 ObjectId('6395010cf760f3c3f2fb96bf'),
 ObjectId('6395010cf760f3c3f2fb96c0'),
 ObjectId('6395010cf760f3c3f2fb96c1'),
 ObjectId('6395010cf760f3c3f2fb96c2'),
 ObjectId('6395010cf760f3c3f2fb96c3'),
 ObjectId('6395010cf760f3c3f2fb96c4'),
 ObjectId('6395010cf760f3c3f2fb96c5'),
 ObjectId('6395010cf760f3c3f2fb96c6'),
 ObjectId('6395010cf760f3c3f2fb96c7'),
 ObjectId('6395010cf760f3c3f2fb96c8'),
 ObjectId('6395010cf760f3c3f2fb96c9'),
 ObjectId('6395010cf760f3c3f2fb96ca'),
 ObjectId('6395010cf760f3c3f2fb96cb'),
 ObjectId('6395010cf760f3c3f2fb96cc'),
 ObjectId('6395010cf760f3c3f2fb96cd'),
 ObjectId('6395010cf760f3c3f2fb96ce'),
 ObjectId('6395010cf760f3c3f2fb96cf'),
 ObjectId('6395010cf760f3c3f2fb96d0'),
 ObjectId('6395010cf760f3c3f2fb96d1'),
 ObjectId('6395010cf760f3c3f2fb96d2'),
 ObjectId('6395010cf760f3c3f2fb96d3'),
 ObjectId('6395010cf760f3c3f2fb96d4'),
 ObjectId('6395010cf760f3c3f2fb96d5'),
 ObjectId('6395010cf760f3c3f2fb96d6'),
 ObjectId('6395010cf760f3c3f2fb96d7'),
 ObjectId('6395010cf760f3c3f2fb96d8'),
 ObjectId('6395010cf760f3c3f2fb96d9'),
 ObjectId('6395010cf760f3c3f2fb96da'),
 ObjectId('6395010cf760f3c3f2fb96db'),
 ObjectId('6395010cf760f3c3f2fb96dc'),
 ObjectId('6395010cf760f3c3f2fb96dd'),
 ObjectId('6395010cf760f3c3f2fb96de'),
 ObjectId('6395010cf760f3c3f2fb96df'),
 ObjectId('6395010cf760f3c3f2fb96e0'),
 ObjectId('6395010cf760f3c3f2fb96e1'),
 ObjectId('6395010cf760f3c3f2fb96e2'),
 ObjectId('6395010cf760f3c3f2fb96e3'),
 ObjectId('6395010cf760f3c3f2fb96e4'),
 ObjectId('6395010cf760f3c3f2fb96e5'),
 ObjectId('6395010cf760f3c3f2fb96e6'),
 ObjectId('6395010cf760f3c3f2fb96e7'),
 ObjectId('6395010cf760f3c3f2fb96e8'),
 ObjectId('6395010cf760f3c3f2fb96e9'),
 ObjectId('6395010cf760f3c3f2fb96ea'),
 ObjectId('6395010cf760f3c3f2fb96eb'),
 ObjectId('6395010cf760f3c3f2fb96ec'),
 ObjectId('6395010cf760f3c3f2fb96ed'),
 ObjectId('6395010cf760f3c3f2fb96ee'),
 ObjectId('6395010cf760f3c3f2fb96ef'),
 ObjectId('6395010cf760f3c3f2fb96f0'),
 ObjectId('6395010cf760f3c3f2fb96f1'),
 ObjectId('6395010cf760f3c3f2fb96f2'),
 ObjectId('6395010cf760f3c3f2fb96f3'),
 ObjectId('6395010cf760f3c3f2fb96f4'),
 ObjectId('6395010cf760f3c3f2fb96f5'),
 ObjectId('6395010cf760f3c3f2fb96f6'),
 ObjectId('6395010cf760f3c3f2fb96f7'),
 ObjectId('6395010cf760f3c3f2fb96f8'),
 ObjectId('6395010cf760f3c3f2fb96f9'),
 ObjectId('6395010cf760f3c3f2fb96fa')]

In [41]:
# start chatbot

import nltk 
# import discord
nltk.download('punkt')

from nltk import word_tokenize,sent_tokenize

from nltk.stem.lancaster import LancasterStemmer
stemmer = LancasterStemmer()
#read more on the steamer https://towardsdatascience.com/stemming-lemmatization-what-ba782b7c0bd8
import numpy as np 
import tflearn
import tensorflow as tf
import random
import json
import pickle

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/maniktuladhar/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

ModuleNotFoundError: No module named 'tflearn'

**Questions:**

(Lasata)

*1. What are the top three highest rated shows of 2020? (general)*
    
   1A: It's Okay Not To Be Okay, The Last Dance, The Queen's Gambit
   
*Alternate Form of Q:*

   Show me the top three highest rated shows of 2020. Show me the top 3 highest rated shows of 2020.
    
    
*2. How many seasons did the top show of 2022 have? (by year)*
    
   2A: 1  
   
*Alternate Form of Q:*

   Show me the number of seasons the top show of 2022 had. Show me the # of seasons the top show of 2022 had.
    
    
*3. For 2018, what shows had an episode duration of 30 minutes or less? (general)*
    
   3A: Derry Girls, Devilman Crybaby, Everything Sucks!, Hilda, On My Block, Rascal Does Not Dream of Bunny Girl          Senpai, She-Ra and the Princesses of Power, The Dragon Prince, The Kominsky Method, Violet Evergarden

*Alternate Form of Q:*

   Show me the shows that had an episode duration of 30 minutes or less. Show me the shows that had an episode            duration of 30 mins or less. Show me the shows that had an episode duration of thirty minutes or less. Show me the    shows that had an episode duration of thirty mins or less.
    
*4. For the highest rated show in 2005, what was its genre? (by year)*
    
   4A: Sci-fi 
   
*Alternate Form of Q:*

   What was the genre of the highest rated show in 2005? Show me the genre of the highest rated show in 2005. 
    
    
*5. Where was the show with the highest rating of 2021 produced? (general)*
    
   5A: US
   
*Alternate Form of Q:*

   Show me where the highest rated show of 2021 was produced. For 2021, where was the highest rated show produced?

---
(Vinya)

*6. In 2008, what was the name of the highest rated show? (by year)*
    
   6A: Breaking Bad
   
*Alternate Form of Q:* 
   
   What was the name of the highest rated show in 2008? Show me    the name of the highest rated show in 2008. 
   
   
*7. What are all the shows that are rated 9.0 and higher? (general)*

   7A: Breaking Bad, Avatar: The Last Airbender, Our Planet, Kota Factory, The Last Dance, Arcane, Attack on Titan,      Hunter x Hunter, DEATH NOTE

*Alternate Form of Q:* 

   Show me the names of all the shows that are rated 9.0 and higher. Show me the names of all the shows that have a      rating of nine and higher.
   
*8. What are all the shows made in Japan after 2000? (by year)*

   8A: Naruto, DEATH NOTE, Hunter x Hunter, Attack on Titan
   
*Alternate Form of Q:* 

   What are all the names of the shows that were made in Japan after 2000? Show me the names of all the shows that        were made in Japan after 2000. 
   
   
*9. What are all the shows that start with the letter W? (general)*

   9A: Workin' Moms, Wild Wild Country, When They See Us, Wentworth
   
*Alternate Form of Q:*    
   
   Show me the names of all the shows that have a title starting with the letter W. What shows have a title that start    with W?
   
   
*10. What shows are 4 seasons long? (by year)*

   10A: Monty Python's Flying Circus, Knight Rider, The 4400, Attack on Titan
   
*Alternate Form of Q:*

   Show me the names of the shows that are four seasons long. Show me the names of the shows that are 4 seasons long.    Show me the titles of the shows that are 4 seasons long. 

---
*11. What is the highest rated show made in 1994? (by year)* 

   11A: There is currently no data on the highest rated show made in 1994.

In [ ]:
# for intents.json file
# change patterns to questions
# change responses to answers